-- =============================================================
-- Esquema de Base de Datos (modular)
-- Proyecto: Cargadores EV Ayuntamiento de Aspe
-- Motor: Supabase (PostgreSQL)
-- =============================================================
--
-- Este archivo actua como indice para ejecutar el esquema por dominio,
-- sin dividirlo en demasiados bloques pequenos.
--
-- Orden recomendado de ejecucion:
-- 1) supabase/schema/10_charging_logs.sql
-- 2) supabase/schema/20_telegram.sql
--
-- Nota:
-- - En el SQL Editor de Supabase, ejecuta cada archivo en este orden.
-- - Si usas psql local, puedes encadenarlos desde consola.
